# Numpy

In [27]:
# Multi dimentional numeric

In [1]:
import numpy as np

In [2]:
n1 = np.array([1,2,3])  # Single dimention
n1

array([1, 2, 3])

In [4]:
n2 = np.array([[1,2,3], [4,5,6], [7,8,9]]) # Multi dimention
n2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(n2)

numpy.ndarray

In [6]:
n3 = np.zeros((4,4))
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
n4 = np.full((2,2),10)
n4

array([[10, 10],
       [10, 10]])

In [11]:
n5 = np.arange(10,20)
n5


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
n6 = np.arange(10,20,2)
n6

array([10, 12, 14, 16, 18])

In [14]:
n7 = np.random.randint(100,200,10)
n7

array([159, 146, 168, 129, 141, 145, 125, 111, 118, 134])

In [15]:
n8 = np.shape(n3)  # Rows and Coloum 
n8

(4, 4)

In [20]:
n1 = np.array([10,20])
n2 = np.array([2,4])
n3 = np.array([1,1])

np.sum([n1,n2,n3])

38

In [21]:
np.sum([n1, n2, n3], axis = 0)   # axis 0 means sum of cols

array([13, 25])

In [22]:
np.sum([n1, n2, n3], axis = 0)   # axis 0 means sum of rows

array([30,  6,  2])

In [24]:
np.vstack((n1,n2,n3))    # Join vertical : 

array([[10, 20],
       [ 2,  4],
       [ 1,  1]])

In [25]:
np.hstack((n1,n2))    # Join Horiz : 

array([10, 20,  2,  4])

In [26]:
np.column_stack((n2,n3))   # Coloum wise 2*2 array

array([[2, 1],
       [4, 1]])